### ISSUE TITLE
Google js API link missing

### ISSUE THREAD

**Issue by rcdevs** [mehdibo/Codeigniter-recaptcha#8]
### Expected behaviour
Seeing Recaptcha
### Actual behaviour
No recaptcha
### Steps to reproduce the behaviour
Install

To solve, add script after closing div box
// Close the box
$box .= '></div>';
$box .=  '<script src="https://www.google.com/recaptcha/api.js?hl=en" async defer></script>';

at the end of the function 	
public function create_box($attr = NULL)
in libraries/Recaptcha.php file

**Comment by mehdibo** [comment]
Read my reply [here](https://github.com/mehdibo/Codeigniter-recaptcha/issues/3)

But I think I should consider adding it to the documentation.

**Comment by rcdevs** [comment]
Yes, 
your readme is well documented, 
and after following all steps, when it doesn't work as expected you wonder if you made something wrong, I was sure something was missing but I spent 10mn to find It was a JS call not included in your scripts. Otherwise Good Job and thank you!
